# Generated by Django 5.2.14 on 2026-05-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='wav_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='transcript',
            name='segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
